---
services:
  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - .:/workspace
    command: sleep infinity
  backend:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    volumes:
      - .:/workspace
    command: sleep infinity
  nginx:
   image: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
   ports:
     - 8080:80
